### ISSUE TITLE
Comparison Against Adam

### ISSUE THREAD

**Issue by JinLi711** [OverLordGoldDragon/keras-adamw#20]
Is it possible for you to benchmark your implementation of AdamW against Tensorflow's implementation of Adam on multiple datasets? It would be useful information for users to decide whether AdamW is the right choice. I would be interested in the differences in the time it takes for every epoch step.

**Comment by OverLordGoldDragon** [comment]
Already done - see [build logs](https://travis-ci.com/OverLordGoldDragon/keras-adamw) based on [tests](https://github.com/OverLordGoldDragon/keras-adamw/tree/master/tests), in particular `test_control()`. Testing isn't exhaustive, but on both sparse and dense data, for a tiny model, the AdamW and TF implementations are about equally fast - and on local tests, same held for a [medium](https://puu.sh/EyjwZ/7a9ac2d113.png) model.
