### ISSUE TITLE
how to log learning_rate 

### ISSUE THREAD

**Issue by michaelwangfeicheng** [OverLordGoldDragon/keras-adamw#60]
Hi, I have used your adamw for my project,but when I log the learning_rate to my log file or tensorboard file with self.optimizer.lr, it always the initial learning_rate. Can you tell me how to log the changing learning_rate at each step ? Thanks

**Comment by OverLordGoldDragon** [comment]
Try `optimizer.lr_t` ([example](https://github.com/OverLordGoldDragon/keras-adamw/blob/v1.38/example.py)).

**Comment by michaelwangfeicheng** [comment]
Thanks
